[package]
name = "bluetooth-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26.0"
crossterm = "0.27.0"
tokio = { version = "1.0", features = ["full"] }
zbus = "4.0"
async-trait = "0.1"
