[package]
name = "wifimanager-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
tui-popup = "0.6"
crossterm = "0.27"
tokio = { version = "1", features = ["full"] }
tokio-wifiscanner = "0.2"
